networks:
  app-network: null
services:
    nginx:
       image: nginx:stable-alpine
       container_name: nginx-fashion-review-app
       ports:
           - '81:80'
       networks:
           - app-network
       volumes:
           - './src:/var/www/html'
           - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
       depends_on:
           - php
           - mariadb
    php:
       image: php:8.2-fpm-alpine
       container_name: php-fashion-review-app
       networks:
           - app-network
       volumes:
           - './src:/var/www/html'
    mariadb:
       image: mariadb:11.6.2
       ports:
          - '3307:3306'
       container_name: mariadb-fashion-review-app
       tty: true
       command: --sql_mode=''
       restart: unless-stopped
       environment:
            MARIADB_ROOT_PASSWORD: 123123
            MARIADB_DATABASE: fashion-review-app
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
       volumes:
           - './src:/var/www/html'
       networks:
           - app-network
    composer:
       image: composer:2.2.24
       container_name: composer-fashion-review-app
       networks:
           - app-network
       volumes:
           - './src:/var/www/html'
    npm:
       image: node:23
       container_name: npm-fashion-review-app
       networks:
           - app-network
       volumes:
           - './src:/var/www/html'


